// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckMusicType(arg1:string):Promise<boolean>;

export function OpenMusicFile():Promise<string>;

export function ParseMusicFile(arg1:string):Promise<main.MusicInfo>;

export function SaveMusicFile(arg1:string,arg2:{[key: string]: string}):Promise<boolean>;
