// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMusicType(arg1) {
  return window['go']['main']['App']['CheckMusicType'](arg1);
}

export function OpenMusicFile() {
  return window['go']['main']['App']['OpenMusicFile']();
}

export function ParseMusicFile(arg1) {
  return window['go']['main']['App']['ParseMusicFile'](arg1);
}

export function SaveMusicFile(arg1, arg2) {
  return window['go']['main']['App']['SaveMusicFile'](arg1, arg2);
}
